### ISSUE TITLE
Sort history by date

### ISSUE THREAD

**Issue by Kurtsley** [Kurtsley/SeedArchive#25]
When the history window is opened, it would be nice to have it sorted by newest at the top.

https://github.com/Kurtsley/SeedArchive/blob/860ad3aa48b323de8784d9aa0f55eb0670b1d6f2/main.py#L265-L278

**Comment by nbeard49** [comment]
There are a couple issues with the current archive DB:
- Not every row has an entry in the 'Date Edited' column as some are NULL (these will show up last in the sort by default)
- Date formatting is different between entries which is going to make sorting this impossible

**To-do:**
- 'Date Edited' should be required on row insertion to the archive table
- Formatting needs to be standardized for all entries in order to sort correctly

I can push the SQL code changes to sort but I'm not able to open the history table or inventory table as I get tkinter exceptions that crash the program on my system (see screenshot):

![tkinter](https://user-images.githubusercontent.com/17462407/145119000-f8866682-006d-438d-9f22-7e849de9ac88.png)
